# Copyright (C) 2021-2023 Tomas Flouri
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: Tomas Flouri <t.flouris@ucl.ac.uk>,
# Department of Genetics, Evolution and Environment,
# University College London, Gower Street, London WC1E 6BT, England

CFLAGS = /W2 /Ox 

AVXDEF=-DHAVE_AVX
AVX2DEF=-DHAVE_AVX2

PROG = bpp-tools.exe

OBJS = bpp-tools.obj util.obj arch.obj hash.obj help.obj phylip.obj maps.obj msa.obj dstat.obj \
     hardware.obj concat.obj compress.obj explode.obj list.obj extract.obj mapping.obj \
     parsemap.obj random.obj remove.obj info.obj hyde.obj treeparse.obj parse.obj \
     fbranch.obj rtree.obj pdfgen.obj visual.obj loci.obj \
     ming2.obj triplet.obj triplet-models.obj

all: $(PROG)

$(PROG): $(OBJS) 
	link /out:$@ $**

clean:
	del *.obj $(PROG)
